/* do you want an rss file to be generated or not? */
int genrss = 1;
/* what to append every html file with */
char *appendhtml = "</article>";
/* what template to use for all html pages */
char *htmltemplate = "template.html";
/* url of website, important for rss */
/* probably change this value */
char *url = "https://alloca.dev";
/* used for rss */
/* you should probably change these values */
char *rsstitle = "website";
char *rssdesc = "website generated by based-ssg";
